package xyz.homapay.hampay.mobile.android.webservice.newpsp;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.12.0
//
// Created by Quasar Development at 10/04/2016
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;

import java.util.List;


public class TWABasicHttpBinding_ITokenPay
{
    interface TWAIWcfMethod
    {
        TWAExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(TWAExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://tokenapp.sep.ir:5412/ThPartyTokenPay.svc";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    TWAIServiceEvents callback;
    public TWABasicHttpBinding_ITokenPay(){}

    public TWABasicHttpBinding_ITokenPay (TWAIServiceEvents callback)
    {
        this.callback = callback;
    }
    public TWABasicHttpBinding_ITokenPay(TWAIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public TWABasicHttpBinding_ITokenPay(TWAIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected TWAExtendedSoapSerializationEnvelope createEnvelope()
    {
        TWAExtendedSoapSerializationEnvelope envelope= new TWAExtendedSoapSerializationEnvelope(TWAExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,TWAExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,TWAExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public TWAArrayOfKeyValueOfstringstring DoWork(final String username,final String password,final String cellnumber,final Integer lang,final TWAArrayOfKeyValueOfstringstring dicData ) throws java.lang.Exception
    {
        return (TWAArrayOfKeyValueOfstringstring)execute(new TWAIWcfMethod()
        {
            @Override
            public TWAExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              TWAExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","dicData",new TWAArrayOfKeyValueOfstringstring().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "DoWork");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="username";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(username!=null?username:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(password!=null?password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="cellnumber";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(cellnumber!=null?cellnumber:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="lang";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(lang!=null?lang:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="dicData";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(dicData!=null?dicData:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(TWAExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (TWAArrayOfKeyValueOfstringstring)getResult(TWAArrayOfKeyValueOfstringstring.class,__result,"DoWorkResult",__envelope);
            }
        },"http://tempuri.org/ITokenPay/DoWork");
    }
    
    public android.os.AsyncTask< Void, Void, TWAOperationResult< TWAArrayOfKeyValueOfstringstring>> DoWorkAsync(final String username,final String password,final String cellnumber,final Integer lang,final TWAArrayOfKeyValueOfstringstring dicData)
    {
        return executeAsync(new TWAFunctions.IFunc< TWAArrayOfKeyValueOfstringstring>() {
            public TWAArrayOfKeyValueOfstringstring Func() throws java.lang.Exception {
                return DoWork( username,password,cellnumber,lang,dicData);
            }
        });
    }

    
    protected java.lang.Object execute(TWAIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        TWAExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, TWAOperationResult< T>>  executeAsync(final TWAFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, TWAOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected TWAOperationResult< T> doInBackground(Void... params) {
                TWAOperationResult< T> result = new TWAOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(TWAOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,TWAExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


