package xyz.homapay.hampay.mobile.android.webservice.newpsp;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.12.0
//
// Created by Quasar Development at 10/04/2016
//
//---------------------------------------------------



public interface TWAIServiceEvents
{
    public void Starting();
    public void Completed(TWAOperationResult result);
}
