package xyz.homapay.hampay.mobile.android.webservice.newpsp;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.12.0
//
// Created by Quasar Development at 10/04/2016
//
//---------------------------------------------------



public class TWAOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;
}
