package xyz.homapay.hampay.mobile.android.webservice.xyz.homapay.hampay.mobile.android.webservice.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.10.0
//
// Created by Quasar Development at 03-02-2016
//
//---------------------------------------------------



public interface HSHIServiceEvents
{
    public void Starting();
    public void Completed(HSHOperationResult result);
}
