package xyz.homapay.hampay.mobile.android.webservice.psp.topup;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 14/01/2017
//
//---------------------------------------------------



public interface HHBIServiceEvents
{
    public void Starting();
    public void Completed(HHBOperationResult result);
}
