package xyz.homapay.hampay.mobile.android.webservice.psp.bills;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.6
//
// Created by Quasar Development at 08/01/2017
//
//---------------------------------------------------



public class MKAOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;
}
